"""The query engine: parse -> look up postings -> intersect -> score -> top-K.

End-to-end path for ``GET /search?q=...``:

1. **Parse.** Split the query into groups: bare terms and quoted phrases.
   Terms go through the same analyzer as documents (lowercase, stopwords,
   Porter) — mandatory, or "Running" would never match "run" in the index.
   A standalone ``OR`` switches from AND (default) to OR semantics.
2. **Look up** each term's posting list from the inverted index.
3. **Intersect** (AND) sorted lists with a two-pointer merge, folding
   **smallest list first**: intersection can only shrink, so every later merge
   scans against the smallest possible left side. For a term in 2 docs AND a
   term in 2 million, work is proportional to the small list, not the big one.
   (OR takes the union instead.)
4. **Phrase check.** For quoted phrases, a document survives only if the terms
   appear at consecutive original-token positions (offset arithmetic on the
   stored positions).
5. **Score** survivors with BM25 and keep the **top K via bounded min-heap** —
   never a full sort of all matches.

Snippets are generated by re-scanning the stored document text for the first
query-stem match and windowing around it. That is O(doc length) per hit at
query time; the production alternative — storing character offsets alongside
positions — trades index space for it. Documented trade-off.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from minisearch.analyze import STOPWORDS, analyze, stem, tokenize
from minisearch.index import InvertedIndex, Posting
from minisearch.rank import BM25, TopK

_SNIPPET_WORDS = 30
_QUERY_RE = re.compile(r'"([^"]*)"|(\S+)')


@dataclass(frozen=True, slots=True)
class SearchHit:
    url: str
    title: str
    score: float
    snippet: str


@dataclass(frozen=True, slots=True)
class _Group:
    """One query group: a single term, or an ordered phrase of terms."""

    terms: tuple[str, ...]              # stemmed
    offsets: tuple[int, ...]            # original-token offsets (phrases)
    is_phrase: bool


def parse_query(q: str) -> tuple[list[_Group], bool]:
    """Return (groups, is_and). Quoted spans become phrase groups; a
    standalone ``OR`` selects union semantics."""
    groups: list[_Group] = []
    is_and = True
    for match in _QUERY_RE.finditer(q):
        phrase, word = match.groups()
        if phrase is not None:
            occs = analyze(phrase)
            if not occs:
                continue
            # Order phrase terms by first occurrence; keep original offsets
            # for the adjacency check.
            ordered = sorted(occs.values(), key=lambda o: o.positions[0])
            base = ordered[0].positions[0]
            groups.append(
                _Group(
                    terms=tuple(o.term for o in ordered),
                    offsets=tuple(o.positions[0] - base for o in ordered),
                    is_phrase=len(ordered) > 1,
                )
            )
        elif word == "OR":
            is_and = False
        else:
            token = word.lower()
            for tok in tokenize(token):
                if tok not in STOPWORDS:
                    groups.append(
                        _Group(terms=(stem(tok),), offsets=(0,), is_phrase=False)
                    )
    return groups, is_and


def intersect(a: list[Posting], b: list[Posting]) -> list[Posting]:
    """Two-pointer merge of doc-id-sorted posting lists; keeps ``a``'s postings.

    O(len(a) + len(b)) — this linearity is the reason posting lists are stored
    sorted. Public so the benchmark can measure fold-order effects directly.
    """
    out: list[Posting] = []
    i = j = 0
    while i < len(a) and j < len(b):
        da, db = a[i].doc_id, b[j].doc_id
        if da == db:
            out.append(a[i])
            i += 1
            j += 1
        elif da < db:
            i += 1
        else:
            j += 1
    return out


class QueryEngine:
    def __init__(self, index: InvertedIndex, k1: float = 1.5, b: float = 0.75) -> None:
        self._index = index
        self._ranker = BM25(index, k1=k1, b=b)

    def search(self, q: str, limit: int = 10) -> list[SearchHit]:
        groups, is_and = parse_query(q)
        if not groups:
            return []

        candidates = self._candidates(groups, is_and)
        if not candidates:
            return []

        # Score every candidate on every query term it contains, keep top K.
        all_terms = {t for g in groups for t in g.terms}
        by_term = {t: {p.doc_id: p for p in self._index.postings(t)} for t in all_terms}
        topk = TopK(limit)
        for doc_id in candidates:
            length = self._index.doc(doc_id).length
            score = sum(
                self._ranker.score(term, docs[doc_id].tf, length)
                for term, docs in by_term.items()
                if doc_id in docs
            )
            topk.offer(score, doc_id)

        stems = {t for g in groups for t in g.terms}
        return [
            SearchHit(
                url=(info := self._index.doc(doc_id)).url,
                title=info.title,
                score=score,
                snippet=make_snippet(info.text, stems),
            )
            for score, doc_id in topk.results()
        ]

    # -- candidate generation ------------------------------------------------

    def _group_docs(self, group: _Group) -> set[int]:
        """Documents matching one group (with phrase adjacency enforced)."""
        lists = [self._index.postings(t) for t in group.terms]
        if any(not lst for lst in lists):
            return set()
        if not group.is_phrase:
            return {p.doc_id for p in lists[0]}

        # AND the phrase's own terms first (smallest list leading)...
        lists_sorted = sorted(lists, key=len)
        shared = lists_sorted[0]
        for other in lists_sorted[1:]:
            shared = intersect(shared, other)
        # ...then keep only docs where terms sit at consecutive offsets.
        position_sets = [
            {p.doc_id: set(p.positions) for p in lst} for lst in lists
        ]
        matched: set[int] = set()
        for posting in shared:
            doc_id = posting.doc_id
            first_positions = position_sets[0][doc_id]
            for start in first_positions:
                if all(
                    start + off in position_sets[k][doc_id]
                    for k, off in enumerate(group.offsets)
                ):
                    matched.add(doc_id)
                    break
        return matched

    def _candidates(self, groups: list[_Group], is_and: bool) -> set[int]:
        doc_sets = [self._group_docs(g) for g in groups]
        if is_and:
            # Fold smallest-first here too: the running intersection only
            # shrinks, so starting small minimizes total comparisons.
            doc_sets.sort(key=len)
            result = doc_sets[0]
            for s in doc_sets[1:]:
                if not result:
                    return set()
                result = result & s
            return result
        return set().union(*doc_sets)


def make_snippet(text: str, stems: set[str], width: int = _SNIPPET_WORDS) -> str:
    """A window of the original text centered on the first query-term match."""
    words = text.split()
    hit = 0
    for i, word in enumerate(words):
        tokens = tokenize(word)
        if tokens and stem(tokens[0]) in stems:
            hit = i
            break
    start = max(0, hit - width // 2)
    end = min(len(words), start + width)
    out = " ".join(words[start:end])
    if start > 0:
        out = "… " + out
    if end < len(words):
        out += " …"
    return out
